### ISSUE TITLE
Hacktoberfest: Text to image search demo update

### ISSUE THREAD

**Issue by iamleonie** [weaviate-tutorials/DEMO-multimodal-text-to-image-search#1]
This is the tracker for polishing the “Text to image search” demo. Please refer to our [Hacktoberfest 2023 blog](https://weaviate.io/blog/hacktoberfest-2023) if you want to contribute! 

List of items to contribute:

- [ ]  Run the existing demo and identify and document what exists and what is or isn’t working for the next task
- [ ]  Fixes for any of the identified issues 
    - [ ] <-- List any identified issues here (e.g., data ingestion, dataset issue, search, back-end/API, front-end) -->
- [ ]  Update README to include:
    - [x] Short description
    - [x] used technology
        - [ ] used Weaviate modules/ML models
    - [ ] Replace screenshots of demo usage with short demo video
    - [x] Prerequisites
    - [x] Setup instructions
    - [x] Usage instructions
    - [x] Dataset license if applicable
    - [ ] Fix broken links (claimed by @ShatilKhan)
- [ ] Possible improvements/enhancements
    - [ ] Add usage of [new multimodal model](https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules/multi2vec-bind)
    - [ ] Replace current sample data with a larger dataset (e.g., from Kaggle)
    - [ ] Add progress bar to import file
    - [ ] Adding tests (e.g., Pytest, Jest, etc. See our [example](https://github.com/databyjp/distyll) for a starting point)
    - [ ] Optional: Conversion to Python (claimed by @CS-Edwards)
        - [ ] Conversion to new [Weaviate Python client](https://weaviate.io/blog/collections-python-client-preview)
        - [ ] After Weaviate release 1.22: swap out preview image

**We're open to further suggestions. If you have any further potential improvement ideas, let us know in the comments!**

📣You can contribute parts of the issue or the whole issue. Please comment below to volunteer for the part(s) you want to contribute to.

❓For any questions you might have along the way, join our [Discourse community forum](https://forum.weaviate.io/t/welcome-to-hacktoberfest-2023/764), where we're ready to answer your questions. Or join our dedicated #hacktoberfest channel in our [Weaviate Community Slack](https://weaviate.slack.com/) channel to stay connected and receive real-time support.

✅For your PR, please mention this issue and set @iamleonie as the reviewer and we will review your PR shortly.

**Comment by anxbt** [comment]
i ran `bash ./import/curl/create_schema.sh` in my git bash it is showing "Failed to connect to localhost port 8080 after 2247 ms: Couldn't connect to server".
p.s - i already have docker desktop running in my backkgorund

**Comment by iamleonie** [comment]
@anxbt It could be that your port 8080 is not open. For me, it worked after following the instructions from this article: https://devicetests.com/fix-curl-7-connection-refused-error

**Comment by Prashanthsai525** [comment]
Hey @iamleonie, I've contributed the Short Description part.

**Comment by iamleonie** [comment]
Thank you so much @Prashanthsai525. Can you please link this issue in the PRs description and set me as reviewer when your PR is ready for review? Please don't hesitate to ping us in Slack or in our forums if you need any assistance.

**Comment by Prashanthsai525** [comment]
> Thank you so much @Prashanthsai525. Can you please link this issue in the PRs description and set me as reviewer when your PR is ready for review? Please don't hesitate to ping us in Slack or in our forums if you need any assistance.

@iamleonie .Can you please review the PR

**Comment by CS-Edwards** [comment]
Hey @iamleonie ,

Quick question for this demo -- would 'conversion to another language (Python) ' task overlap with the 'conversion to new Weaviate Python client' task? I'm happy to take this on if available.

**Comment by iamleonie** [comment]
Hey @CS-Edwards, good point. Yes, you are right: 'conversion to another language (Python)' could overlap with 'conversion to new Weaviate Python client'. 
If you decide to convert the project to Python, you could directly convert it using the new Weaviate Python client or you could use the old one and someone else could later add the new Python client. 
I am fine with both solutions. Please let us know what option you decide on.

**Comment by CS-Edwards** [comment]
Thanks @iamleonie! I will convert to python  + add the new Python client

**Comment by ShatilKhan** [comment]
Hi @iamleonie 
I'll be contributing to Fix Broken Links in README

**Comment by ShatilKhan** [comment]
Thanks!

**Comment by iamleonie** [comment]
Hey @ShatilKhan  and @CS-Edwards,
since it's the last week of Hacktoberfest, I wanted to quickly check in with you to see how things are going.
Please don't hesitate to reach out here or on our [Community Slack](https://weaviate.io/slack) if you need any assistance.
We can also un-claim the tasks if you are no longer working on the tasks.

**Comment by CS-Edwards** [comment]
Hey @iamleonie ! Thanks for checking in -- I am hoping to submit my PRs by the end of the weekend.

**Comment by CS-Edwards** [comment]
Hey @iamleonie ! Just an FYI I have two open PRs at the moment. I left notes on the request. 

Also :
- I'm releasing/unclaiming the Python new client issue, I am working on the python demo (reflected in PRs).

- I've added the demo video to the readme

Cheers,
C

**Comment by iamleonie** [comment]
Thank you, everyone, for contributing to a successful Hacktoberfest 2023!

This issue will now be closed.

If you are still working on any topics, you can, of course, continue on them. However, please note that any PRs created after Oct 31st will not count towards Hacktoberfest.
